version: 0.2
env:
    secrets-manager:
        TOKEN: firstSecret:sonarToken
phases:
  install:
    runtime-versions:
      java: latest
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=javaprojectaws9 -Dsonar.organization=javaprojectaws9 -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$TOKEN
